entrada = input('Digite alguma coisa: ')
print('A entrada é númerica?', entrada.isnumeric())
print('A entrada é ASCII?', entrada.isascii())
print('A entrada é um decimal', entrada.isdecimal())
print('A entrada é um digito?', entrada.isdigit())
print('A entrada é minuscula?', entrada.islower())
print('A entrada so tem espaço?', entrada.isspace())
print('A entrada está capitalizada?', entrada.istitle())
print('A entrada é é maiscula?', entrada.isupper())
