listagem = ('Lápis', 1.75, 'Borracha',2.00,'Caderno',15.9,'Estojo',25.00,'Transferidor',4.20,)

print('-'*31)
print('      LISTAGEM DE PREÇOS')
print('-'*31)
print(listagem[0],'................', 'R$ ',listagem[1])
print(listagem[2],'.............', 'R$ ',listagem[3])
print(listagem[4],'..............', 'R$ ',listagem[5])
print(listagem[6],'...............', 'R$ ',listagem[7])
print(listagem[8],'.........', 'R$ ',listagem[9])
print('-'*31)